name: "Build tree on REPLACE_DATE"

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build-tree:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run:
         sed -i 's/REPLACE_DATE/2021-01-01/g' default.nix
  
    - run:   |
         if [ "$RUNNER_OS" == "Linux" ]; then
              nix-build --keep-going --max-jobs 1 --cores 2 --argstr system x86_64-linux cachix.nix
              nix-build --keep-going --max-jobs 1 --cores 2 --argstr system aarch64-linux cachix.nix
         else
              nix-build --keep-going --max-jobs 1 --cores 2 cachix.nix
         fi
        
    - run: nix-store -qR --include-outputs $(nix-instantiate cachix.nix) | cachix push rstats-on-nix
    - run: nix-shell cachix.nix --run "echo OK"
