name: Trigger build for available dates in rix

on:
  schedule:
    - cron: '0 23 * * 1'
  push:
    branches:
      - build_tree

jobs:
  update-and-trigger-ubuntu:
    name: Trigger build for available dates on Ubuntu
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.MY_PAT }}
      GITHUB_TOKEN: ${{ secrets.MY_PAT }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}

      - name: Set branch_date as today
        id: set_date
        #run: echo "branch_date=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
        run: echo "branch_date=2025-01-18" >> $GITHUB_ENV

      - name: Update default.nix
        run: |
          sed -i 's/REPLACE_DATE/${{ env.branch_date }}/g' default.nix

      - name: Build on date ${{ github.event.client_payload.ref_name }}
        run: |
          nix-build --max-jobs 1 --cores 2 default.nix

  update-and-trigger-macos:
    name: Trigger build for available dates on macOS
    runs-on: macos-latest
    needs: update-and-trigger-ubuntu
    env:
      GITHUB_PAT: ${{ secrets.MY_PAT }}
      GITHUB_TOKEN: ${{ secrets.MY_PAT }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}

      - name: Set branch_date as today
        id: set_date
        run: echo "branch_date=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Update default.nix
        run: |
          sed -i '' 's/REPLACE_DATE/${{ env.branch_date }}/g' default.nix

      - name: Build on date ${{ github.event.client_payload.ref_name }}
        run: |
          nix-build --max-jobs 1 --cores 2 default.nix

  clone-and-open-pr:
      name: Clone rix and open PR
      runs-on: ubuntu-latest
      needs: update-and-trigger-macos
      env:
        GITHUB_PAT: ${{ secrets.MY_PAT }}
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
  
      steps:
        - name: Clone rix and open PR
          run: |
            curl -X POST \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ropensci/rix/dispatches \
            -d '{
              "event_type": "trigger-workflow",
              "client_payload": {
                "branch_date": "${{ env.branch_date }}"
              }
            }'